### ISSUE TITLE
design issue

### ISSUE THREAD

**Issue by pavanitester** [Muthuvelm/P0253-One-page-website-for-Enterprise-#5]
![screenshot_10](https://user-images.githubusercontent.com/39519970/41852600-3fb44754-78a9-11e8-8c04-d103660b0925.png)
![screenshot_16](https://user-images.githubusercontent.com/39519970/41852601-3fead58a-78a9-11e8-997f-229d50f91eb0.png)
![screenshot_19](https://user-images.githubusercontent.com/39519970/41852602-4041bf8a-78a9-11e8-8d67-ca3dba7e3322.png)

**Comment by raju-designer** [comment]
2nd image has difficult to acheive, its take some time.
3rd image has been fixed

**Comment by pavanitester** [comment]
ok
